# Generated by Django 4.1.4 on 2024-11-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
