# Generated by Django 4.1.4 on 2024-11-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksWeb', '0003_feedback_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
