# Generated by Django 4.1.4 on 2024-11-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksWeb', '0004_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
